// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgc5WRGOceqw_20qUx-Q64Ta7DUiSqW7k',
    appId: '1:910861966895:web:6be5a7b136955fd886b0da',
    messagingSenderId: '910861966895',
    projectId: 'whatsapp-5ce1f',
    authDomain: 'whatsapp-5ce1f.firebaseapp.com',
    storageBucket: 'whatsapp-5ce1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9zYZvSuAhtTHlnfn2ZG2ze6boNe_lIJY',
    appId: '1:910861966895:android:0318b0dbd3d7e6a886b0da',
    messagingSenderId: '910861966895',
    projectId: 'whatsapp-5ce1f',
    storageBucket: 'whatsapp-5ce1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_NtzqsrsZtnZcvQY5iGMVS-Ho445Hc_4',
    appId: '1:910861966895:ios:f1c980a352ec408986b0da',
    messagingSenderId: '910861966895',
    projectId: 'whatsapp-5ce1f',
    storageBucket: 'whatsapp-5ce1f.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_NtzqsrsZtnZcvQY5iGMVS-Ho445Hc_4',
    appId: '1:910861966895:ios:fde472c02f3d429a86b0da',
    messagingSenderId: '910861966895',
    projectId: 'whatsapp-5ce1f',
    storageBucket: 'whatsapp-5ce1f.appspot.com',
    iosBundleId: 'com.example.whatsappClone.RunnerTests',
  );
}
